import type { Diagram } from "./types";

export const demoDiagram: Diagram = {
  title: "skill-architecture",
  sourceName: "abel-works-lab/skill-architecture",
  summary: "スキルフォルダを読み、構成要素と処理フローをインタラクティブなアーキテクチャ図に変換する。",
  nodes: [
    {
      id: "user_request",
      label: "ユーザー入力",
      cat: "external",
      role: "可視化したいスキルフォルダを指定する",
      desc: "ユーザーは .claude/skills などの親フォルダを指定する。各サブフォルダが分析対象のスキルとして扱われる。",
      x: 40,
      y: 170,
    },
    {
      id: "skill_entry",
      label: "SKILL.md",
      cat: "entry",
      role: "処理ルールと出力仕様の起点",
      desc: "トリガーワード、読むべきファイル、ノード分類、検証手順を定義する中心ドキュメント。",
      x: 250,
      y: 120,
    },
    {
      id: "folder_scan",
      label: "フォルダスキャン",
      cat: "tool",
      role: "サブフォルダと主要ファイルを列挙する",
      desc: "対象フォルダ直下のサブフォルダをタブ候補として抽出し、agents / scripts / workflows などの構成を確認する。",
      x: 470,
      y: 120,
    },
    {
      id: "analysis_rules",
      label: "分析ルール",
      cat: "detail",
      role: "エントリーポイントと補助資料を読む順序",
      desc: "SKILL.md、AGENTS.md、README.md、重要なサブドキュメントの順に読み、スキルの入出力と主要な処理を整理する。",
      x: 690,
      y: 70,
    },
    {
      id: "template_html",
      label: "template.html",
      cat: "config",
      role: "インタラクティブ図の描画テンプレート",
      desc: "タブ、ドラッグ、ズーム、付箋、フローハイライト、右パネルを含む単体 HTML テンプレート。",
      x: 690,
      y: 190,
    },
    {
      id: "skills_data",
      label: "SKILLS_DATA",
      cat: "parallel",
      role: "ノード・接続・フローの構造化データ",
      desc: "各スキルの nodes、connections、flows を JSON ライクな構造に落とし込み、テンプレートに注入する。",
      x: 930,
      y: 120,
    },
    {
      id: "validation",
      label: "検証",
      cat: "tool",
      role: "ID、接続、currentSkillId をチェックする",
      desc: "ノード ID 重複、flow.conns と connections の一致、存在しないノード参照などを生成後に確認する。",
      x: 1150,
      y: 120,
    },
    {
      id: "html_output",
      label: "HTML 出力",
      cat: "output",
      role: "ブラウザで開ける成果物",
      desc: "output/html/skill-architecture_{ver}.html として、番号を増やしながら新しい可視化 HTML を生成する。",
      x: 1370,
      y: 120,
    },
  ],
  connections: [
    { from: "user_request", to: "skill_entry", type: "normal", label: "trigger" },
    { from: "skill_entry", to: "folder_scan", type: "normal" },
    { from: "folder_scan", to: "analysis_rules", type: "normal" },
    { from: "folder_scan", to: "template_html", type: "dashed", label: "base" },
    { from: "analysis_rules", to: "skills_data", type: "par" },
    { from: "template_html", to: "skills_data", type: "normal" },
    { from: "skills_data", to: "validation", type: "normal" },
    { from: "validation", to: "html_output", type: "normal" },
  ],
  flows: [
    {
      id: "main_flow",
      name: "生成フロー",
      desc: "フォルダ指定から HTML 出力までの主経路。",
      nodes: ["user_request", "skill_entry", "folder_scan", "analysis_rules", "skills_data", "validation", "html_output"],
      conns: ["user_request→skill_entry", "skill_entry→folder_scan", "folder_scan→analysis_rules", "analysis_rules→skills_data", "skills_data→validation", "validation→html_output"],
      steps: [
        { n: 1, text: "対象フォルダを受け取る", detail: "ユーザーが指定したパスを基点にサブフォルダを列挙する。", exec: "claude" },
        { n: 2, text: "構造を読む", detail: "エントリーポイントと補助ドキュメントからノード候補を抽出する。", exec: "claude" },
        { n: 3, text: "図データ化する", detail: "ノード、接続、フロー、ステップを SKILLS_DATA として組み立てる。", exec: "claude" },
        { n: 4, text: "検証して出力する", detail: "参照整合性を確認し、ブラウザで開ける HTML として保存する。", exec: "claude" },
      ],
    },
    {
      id: "template_flow",
      name: "テンプレート活用",
      desc: "既存のインタラクションを保ったままデータだけ差し替える経路。",
      nodes: ["template_html", "skills_data", "validation", "html_output"],
      conns: ["template_html→skills_data", "skills_data→validation", "validation→html_output"],
      steps: [
        { n: 1, text: "template.html を基盤にする", detail: "ドラッグ、ズーム、付箋、右パネルなどの実装済み機能を活用する。", exec: "claude" },
        { n: 2, text: "SKILLS_DATA を差し替える", detail: "可視化対象ごとのデータだけを安全に置換する。", exec: "claude" },
      ],
    },
  ],
};
